// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataAccess.Models
{
    public partial class Learning
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string ComesUnder { get; set; }
        public int PriorityId { get; set; }
        public string Status { get; set; }
        public DateTime? FirstPicked { get; set; }
        public DateTime? LastVisit { get; set; }
    }
}