# For more info on HTTP files go to https://aka.ms/vs/httpfile

###
GET https://localhost:7069/api/transactions
Accept: application/json

###
GET https://localhost:7069/api/transactions/1
Accept: application/json

###
POST https://localhost:7069/api/transactions
Accept: application/json
Content-Type:application/json

{
  "item": "Ticket",
  "amount": 6969.96,
  "categoryId": 11,
  "comment": "Trip to Heaven"
}

###
PUT https://localhost:7069/api/transactions/update/16
Accept: application/json
Content-Type:application/json

{
  "item": "Ticket",
  "amount": 6969.96,
  "categoryId": 11,
  "comment": "Trip to Heaven"
}

###
DELETE https://localhost:7069/api/transactions/delete/17
Accept: application/json