# For more info on HTTP files go to https://aka.ms/vs/httpfile

###
GET https://localhost:7069/api/transactions
Accept: application/json

###
GET https://localhost:7069/api/transactions?id=1
Accept: application/json

###
POST https://localhost:7069/api/transactions/add
Accept: application/json
Content-Type:application/json

{
  "item": "Ticket",
  "amount": 6969.96,
  "categoryId": 11,
  "comment": "Trip to Heaven"
}

###
PUT https://localhost:7069/api/transactions/update?id=16
Accept: application/json
Content-Type:application/json

{
  "item": "Ticket",
  "amount": 6969.96,
  "categoryId": 11,
  "comment": "Trip to Heaven"
}

###
DELETE https://localhost:7069/api/transactions/delete?id=17
Accept: application/json